source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Passenger_Example', :exclusive => true do
    pod "Passenger", :path => "../"
end

target 'Passenger_Tests', :exclusive => true do
    pod "Passenger", :path => "../"

    #pod 'FBSnapshotTestCase'
end

pod 'Wildcard'