source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Albatross_Example', :exclusive => true do
    pod "Albatross", :path => "../"
end

target 'Albatross_Tests', :exclusive => true do
    pod "Albatross", :path => "../"

    #pod 'FBSnapshotTestCase'
end

pod 'Wildcard'